######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 5 17:50:51 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += App.cpp
