######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 16:52:08 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += ./src/test.cpp
SOURCES += src/App.cpp src/test.cpp

# Output
OBJECTS_DIR = obj
